package main

type NistComp struct {
	Provider      string
	Framework     string
	Frameworkdesc string
	Id            string
	Name          string
	Description   string
	Category      string
	Objetive_ID   string
	Objetive_Name string
	Check_Summary string
	Checks        []string
}

var ISO27001_A_10_1_1 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.10.1",
	Name:          "Cryptographic Controls",
	Description:   "Setup Encryption at rest for RDS instances",
	Category:      "A.10 Cryptography",
	Objetive_ID:   "A.10.1",
	Objetive_Name: "Cryptographic Controls",
	Check_Summary: "Setup Encryption at rest for RDS instances",
	Checks:        []string{"rds_instance_storage_encrypted"},
}
var ISO27001_A_10_1_2 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.10.1",
	Name:          "Cryptographic Controls",
	Description:   "Detect use of insecure ciphers on ELBs",
	Category:      "A.10 Cryptography",
	Objetive_ID:   "A.10.1",
	Objetive_Name: "Cryptographic Controls",
	Check_Summary: "Detect use of insecure ciphers on ELBs",
	Checks:        []string{"elb_insecure_ssl_ciphers", "elbv2_insecure_ssl_ciphers"},
}
var ISO27001_A_10_1_3 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.10.1",
	Name:          "Cryptographic Controls",
	Description:   "Detect Customer Master Keys (CMKs) scheduled for deletion",
	Category:      "A.10 Cryptography",
	Objetive_ID:   "A.10.1",
	Objetive_Name: "Cryptographic Controls",
	Check_Summary: "Detect Customer Master Keys (CMKs) scheduled for deletion",
	Checks:        []string{"cloudwatch_log_metric_filter_disable_or_scheduled_deletion_of_kms_cmk"},
}
var ISO27001_A_12_4_1 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for VPC changes",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for VPC changes",
	Checks:        []string{"cloudwatch_changes_to_vpcs_alarm_configured"},
}
var ISO27001_A_12_4_2 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for route table changes",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for route table changes",
	Checks:        []string{"cloudwatch_changes_to_network_route_tables_alarm_configured"},
}
var ISO27001_A_12_4_3 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for changes to network gateways",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for changes to network gateways",
	Checks:        []string{"cloudwatch_changes_to_network_gateways_alarm_configured"},
}
var ISO27001_A_12_4_4 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for changes to Network Access Control Lists (NACL)",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for changes to Network Access Control Lists (NACL)",
	Checks:        []string{"cloudwatch_changes_to_network_acls_alarm_configured"},
}
var ISO27001_A_12_4_5 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for security group changes",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for security group changes",
	Checks:        []string{"cloudwatch_log_metric_filter_security_group_changes"},
}
var ISO27001_A_12_4_6 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for AWS Config configuration changes",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for AWS Config configuration changes",
	Checks:        []string{"cloudwatch_log_metric_filter_and_alarm_for_aws_config_configuration_changes_enabled"},
}
var ISO27001_A_12_4_7 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for S3 bucket policy changes",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for S3 bucket policy changes",
	Checks:        []string{"cloudwatch_log_metric_filter_for_s3_bucket_policy_changes"},
}
var ISO27001_A_12_4_8 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for disabling or scheduled deletion of customer created CMKs",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for disabling or scheduled deletion of customer created CMKs",
	Checks:        []string{"cloudwatch_log_metric_filter_disable_or_scheduled_deletion_of_kms_cmk"},
}
var ISO27001_A_12_4_9 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for AWS Management Console authentication failures",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for AWS Management Console authentication failures",
	Checks:        []string{"cloudwatch_log_metric_filter_authentication_failures"},
}
var ISO27001_A_12_4_10 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for CloudTrail configuration changes",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for CloudTrail configuration changes",
	Checks:        []string{"cloudwatch_log_metric_filter_and_alarm_for_cloudtrail_configuration_changes_enabled"},
}
var ISO27001_A_12_4_11 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for IAM policy changes",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for IAM policy changes",
	Checks:        []string{"cloudwatch_log_metric_filter_policy_changes"},
}
var ISO27001_A_12_4_12 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for usage of root account",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for usage of root account",
	Checks:        []string{"cloudwatch_log_metric_filter_root_usage"},
}
var ISO27001_A_12_4_13 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for Management Console sign-in without MFA",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for Management Console sign-in without MFA",
	Checks:        []string{"cloudwatch_log_metric_filter_sign_in_without_mfa"},
}
var ISO27001_A_12_4_14 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure a log metric filter and alarm exist for unauthorized API calls",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure a log metric filter and alarm exist for unauthorized API calls",
	Checks:        []string{"cloudwatch_log_metric_filter_unauthorized_api_calls"},
}
var ISO27001_A_12_4_15 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket",
	Checks:        []string{"cloudtrail_logs_s3_bucket_access_logging_enabled"},
}
var ISO27001_A_12_4_16 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure AWS Config is enabled in all regions",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure AWS Config is enabled in all regions",
	Checks:        []string{"config_recorder_all_regions_enabled"},
}
var ISO27001_A_12_4_17 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure CloudTrail trails are integrated with CloudWatch Logs",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure CloudTrail trails are integrated with CloudWatch Logs",
	Checks:        []string{"cloudtrail_cloudwatch_logging_enabled"},
}
var ISO27001_A_12_4_18 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure VPC flow logging is enabled in all VPCs",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure VPC flow logging is enabled in all VPCs",
	Checks:        []string{"vpc_flow_logs_enabled"},
}
var ISO27001_A_12_4_19 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure the S3 bucket CloudTrail logs to is not publicly accessible",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure the S3 bucket CloudTrail logs to is not publicly accessible",
	Checks:        []string{"cloudtrail_logs_s3_bucket_is_not_publicly_accessible"},
}
var ISO27001_A_12_4_20 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.4",
	Name:          "Logging and Monitoring",
	Description:   "Ensure CloudTrail is enabled in all regions",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.4",
	Objetive_Name: "Logging and Monitoring",
	Check_Summary: "Ensure CloudTrail is enabled in all regions",
	Checks:        []string{"cloudtrail_multi_region_enabled"},
}
var ISO27001_A_12_6 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.6",
	Name:          "Technical Vulnerability Management",
	Description:   "Ensure the default security group of every VPC restricts all traffic",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.6",
	Objetive_Name: "Technical Vulnerability Management",
	Check_Summary: "Ensure the default security group of every VPC restricts all traffic",
	Checks:        []string{"ec2_securitygroup_default_restrict_traffic"},
}
var ISO27001_A_12_6_1 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.6",
	Name:          "Technical Vulnerability Management",
	Description:   "Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.6",
	Objetive_Name: "Technical Vulnerability Management",
	Check_Summary: "Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389",
	Checks:        []string{"ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_3389"},
}
var ISO27001_A_12_6_2 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.6",
	Name:          "Technical Vulnerability Management",
	Description:   "Ensure no security groups allow ingress from 0.0.0.0/0 to port 22",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.6",
	Objetive_Name: "Technical Vulnerability Management",
	Check_Summary: "Ensure no security groups allow ingress from 0.0.0.0/0 to port 22",
	Checks:        []string{"ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_22"},
}
var ISO27001_A_12_6_3 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.6",
	Name:          "Technical Vulnerability Management",
	Description:   "Check for publicly shared AMIs",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.6",
	Objetive_Name: "Technical Vulnerability Management",
	Check_Summary: "Check for publicly shared AMIs",
	Checks:        []string{"ec2_ami_public"},
}
var ISO27001_A_12_6_4 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.6",
	Name:          "Technical Vulnerability Management",
	Description:   "Ensure EBS snapshots are not publicly accessible",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.6",
	Objetive_Name: "Technical Vulnerability Management",
	Check_Summary: "Ensure EBS snapshots are not publicly accessible",
	Checks:        []string{"ec2_ebs_public_snapshot"},
}
var ISO27001_A_12_6_5 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.6",
	Name:          "Technical Vulnerability Management",
	Description:   "Ensure SNS topics do not allow global send or subscribe",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.6",
	Objetive_Name: "Technical Vulnerability Management",
	Check_Summary: "Ensure SNS topics do not allow global send or subscribe",
	Checks:        []string{"sns_topics_not_publicly_accessible"},
}
var ISO27001_A_12_6_6 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.6",
	Name:          "Technical Vulnerability Management",
	Description:   "Ensure Redshift clusters do not have a public endpoint",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.6",
	Objetive_Name: "Technical Vulnerability Management",
	Check_Summary: "Ensure Redshift clusters do not have a public endpoint",
	Checks:        []string{"redshift_cluster_public_access"},
}
var ISO27001_A_12_6_7 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.6",
	Name:          "Technical Vulnerability Management",
	Description:   "Ensure RDS snapshots are not publicly accessible",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.6",
	Objetive_Name: "Technical Vulnerability Management",
	Check_Summary: "Ensure RDS snapshots are not publicly accessible",
	Checks:        []string{"rds_snapshots_public_access"},
}
var ISO27001_A_12_6_8 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.6",
	Name:          "Technical Vulnerability Management",
	Description:   "Ensure RDS instances are not accessible to the world.",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.6",
	Objetive_Name: "Technical Vulnerability Management",
	Check_Summary: "Ensure RDS instances are not accessible to the world.",
	Checks:        []string{"rds_instance_no_public_access"},
}
var ISO27001_A_12_6_9 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.12.6",
	Name:          "Technical Vulnerability Management",
	Description:   "Ensure the S3 bucket CloudTrail logs to is not publicly accessible",
	Category:      "A.12 Operations Security",
	Objetive_ID:   "A.12.6",
	Objetive_Name: "Technical Vulnerability Management",
	Check_Summary: "Ensure the S3 bucket CloudTrail logs to is not publicly accessible",
	Checks:        []string{"cloudtrail_logs_s3_bucket_is_not_publicly_accessible"},
}
var ISO27001_A_13_1_1 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.13.1",
	Name:          "Network Security Management",
	Description:   "Ensure the default security group of every VPC restricts all traffic",
	Category:      "A.13 Communications Security",
	Objetive_ID:   "A.13.1",
	Objetive_Name: "Network Security Management",
	Check_Summary: "Ensure the default security group of every VPC restricts all traffic",
	Checks:        []string{"ec2_securitygroup_default_restrict_traffic"},
}
var ISO27001_A_13_1_2 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.13.1",
	Name:          "Network Security Management",
	Description:   "Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389",
	Category:      "A.13 Communications Security",
	Objetive_ID:   "A.13.1",
	Objetive_Name: "Network Security Management",
	Check_Summary: "Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389",
	Checks:        []string{"ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_3389"},
}
var ISO27001_A_13_1_3 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.13.1",
	Name:          "Network Security Management",
	Description:   "Ensure no security groups allow ingress from 0.0.0.0/0 to port 22",
	Category:      "A.13 Communications Security",
	Objetive_ID:   "A.13.1",
	Objetive_Name: "Network Security Management",
	Check_Summary: "Ensure no security groups allow ingress from 0.0.0.0/0 to port 22",
	Checks:        []string{"ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_22"},
}
var ISO27001_A_13_1_4 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.13.1",
	Name:          "Network Security Management",
	Description:   "Ensure EBS snapshots are not publicly accessible",
	Category:      "A.13 Communications Security",
	Objetive_ID:   "A.13.1",
	Objetive_Name: "Network Security Management",
	Check_Summary: "Ensure EBS snapshots are not publicly accessible",
	Checks:        []string{"ec2_ebs_public_snapshot"},
}
var ISO27001_A_13_1_5 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.13.1",
	Name:          "Network Security Management",
	Description:   "Ensure SNS topics do not allow global send or subscribe",
	Category:      "A.13 Communications Security",
	Objetive_ID:   "A.13.1",
	Objetive_Name: "Network Security Management",
	Check_Summary: "Ensure SNS topics do not allow global send or subscribe",
	Checks:        []string{"sns_topics_not_publicly_accessible"},
}
var ISO27001_A_13_1_6 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.13.1",
	Name:          "Network Security Management",
	Description:   "Ensure Redshift clusters do not have a public endpoint",
	Category:      "A.13 Communications Security",
	Objetive_ID:   "A.13.1",
	Objetive_Name: "Network Security Management",
	Check_Summary: "Ensure Redshift clusters do not have a public endpoint",
	Checks:        []string{"redshift_cluster_public_access"},
}
var ISO27001_A_13_1_7 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.13.1",
	Name:          "Network Security Management",
	Description:   "Ensure RDS snapshots are not publicly accessible",
	Category:      "A.13 Communications Security",
	Objetive_ID:   "A.13.1",
	Objetive_Name: "Network Security Management",
	Check_Summary: "Ensure RDS snapshots are not publicly accessible",
	Checks:        []string{"rds_snapshots_public_access"},
}
var ISO27001_A_13_1_8 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.13.1",
	Name:          "Network Security Management",
	Description:   "Ensure RDS instances are not accessible to the world.",
	Category:      "A.13 Communications Security",
	Objetive_ID:   "A.13.1",
	Objetive_Name: "Network Security Management",
	Check_Summary: "Ensure RDS instances are not accessible to the world.",
	Checks:        []string{"rds_instance_no_public_access"},
}
var ISO27001_A_9_2_1 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure IAM password policy expires passwords within 90 days or less",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure IAM password policy expires passwords within 90 days or less",
	Checks:        []string{"iam_password_policy_expires_passwords_within_90_days_or_less"},
}
var ISO27001_A_9_2_2 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure IAM password policy prevents password reuse",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure IAM password policy prevents password reuse",
	Checks:        []string{"iam_password_policy_reuse_24"},
}
var ISO27001_A_9_2_3 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure IAM password policy requires minimum length of 14 or greater",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure IAM password policy requires minimum length of 14 or greater",
	Checks:        []string{"iam_password_policy_minimum_length_14"},
}
var ISO27001_A_9_2_4 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure IAM password policy require at least one number",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure IAM password policy require at least one number",
	Checks:        []string{"iam_password_policy_number"},
}
var ISO27001_A_9_2_5 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure IAM password policy require at least one symbol",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure IAM password policy require at least one symbol",
	Checks:        []string{"iam_password_policy_symbol"},
}
var ISO27001_A_9_2_6 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure IAM password policy require at least one lowercase letter",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure IAM password policy require at least one lowercase letter",
	Checks:        []string{"iam_password_policy_lowercase"},
}
var ISO27001_A_9_2_7 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure IAM password policy requires at least one uppercase letter",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure IAM password policy requires at least one uppercase letter",
	Checks:        []string{"iam_password_policy_uppercase"},
}
var ISO27001_A_9_2_8 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Avoid the use of the 'root' account",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Avoid the use of the 'root' account",
	Checks:        []string{"iam_avoid_root_usage"},
}
var ISO27001_A_9_2_9 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure IAM policies are attached only to groups or roles",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure IAM policies are attached only to groups or roles",
	Checks:        []string{"iam_policy_attached_only_to_group_or_roles"},
}
var ISO27001_A_9_2_10 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure multi-factor authentication (MFA) is enabled for all IAM users that have console access",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure multi-factor authentication (MFA) is enabled for all IAM users that have console access",
	Checks:        []string{"iam_user_mfa_enabled_console_access"},
}
var ISO27001_A_9_2_11 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure MFA is enabled for the 'root' account",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure MFA is enabled for the 'root' account",
	Checks:        []string{"iam_root_mfa_enabled"},
}
var ISO27001_A_9_2_12 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure access keys are rotated every 90 days or less",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure access keys are rotated every 90 days or less",
	Checks:        []string{"iam_rotate_access_key_90_days"},
}
var ISO27001_A_9_2_13 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure credentials unused for 90 days or greater are disabled",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure credentials unused for 90 days or greater are disabled",
	Checks:        []string{"iam_user_accesskey_unused", "iam_user_console_access_unused"},
}
var ISO27001_A_9_2_14 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.2",
	Name:          "User Access Management",
	Description:   "Ensure no root account access key exists",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.2",
	Objetive_Name: "User Access Management",
	Check_Summary: "Ensure no root account access key exists",
	Checks:        []string{"iam_no_root_access_key"},
}
var ISO27001_A_9_3_1 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.3",
	Name:          "User Responsibilities",
	Description:   "Ensure IAM password policy expires passwords within 90 days or less",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.3",
	Objetive_Name: "User Responsibilities",
	Check_Summary: "Ensure IAM password policy expires passwords within 90 days or less",
	Checks:        []string{"iam_password_policy_expires_passwords_within_90_days_or_less"},
}
var ISO27001_A_9_3_2 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.3",
	Name:          "User Responsibilities",
	Description:   "Ensure IAM password policy prevents password reuse",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.3",
	Objetive_Name: "User Responsibilities",
	Check_Summary: "Ensure IAM password policy prevents password reuse",
	Checks:        []string{"iam_password_policy_reuse_24"},
}
var ISO27001_A_9_3_3 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.3",
	Name:          "User Responsibilities",
	Description:   "Ensure IAM password policy requires minimum length of 14 or greater",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.3",
	Objetive_Name: "User Responsibilities",
	Check_Summary: "Ensure IAM password policy requires minimum length of 14 or greater",
	Checks:        []string{"iam_password_policy_minimum_length_14"},
}
var ISO27001_A_9_3_4 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.3",
	Name:          "User Responsibilities",
	Description:   "Ensure IAM password policy require at least one number",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.3",
	Objetive_Name: "User Responsibilities",
	Check_Summary: "Ensure IAM password policy require at least one number",
	Checks:        []string{"iam_password_policy_number"},
}
var ISO27001_A_9_3_5 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.3",
	Name:          "User Responsibilities",
	Description:   "Ensure IAM password policy require at least one symbol",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.3",
	Objetive_Name: "User Responsibilities",
	Check_Summary: "Ensure IAM password policy require at least one symbol",
	Checks:        []string{"iam_password_policy_symbol"},
}
var ISO27001_A_9_3_6 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.3",
	Name:          "User Responsibilities",
	Description:   "Ensure IAM password policy require at least one lowercase letter",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.3",
	Objetive_Name: "User Responsibilities",
	Check_Summary: "Ensure IAM password policy require at least one lowercase letter",
	Checks:        []string{"iam_password_policy_lowercase"},
}
var ISO27001_A_9_3_7 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.3",
	Name:          "User Responsibilities",
	Description:   "Ensure IAM password policy requires at least one uppercase letter",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.3",
	Objetive_Name: "User Responsibilities",
	Check_Summary: "Ensure IAM password policy requires at least one uppercase letter",
	Checks:        []string{"iam_password_policy_uppercase"},
}
var ISO27001_A_9_3_8 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.3",
	Name:          "User Responsibilities",
	Description:   "Ensure multi-factor authentication (MFA) is enabled for all IAM users that have console access",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.3",
	Objetive_Name: "User Responsibilities",
	Check_Summary: "Ensure multi-factor authentication (MFA) is enabled for all IAM users that have console access",
	Checks:        []string{"iam_user_mfa_enabled_console_access"},
}
var ISO27001_A_9_3_9 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.3",
	Name:          "User Responsibilities",
	Description:   "Ensure access keys are rotated every 90 days or less",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.3",
	Objetive_Name: "User Responsibilities",
	Check_Summary: "Ensure access keys are rotated every 90 days or less",
	Checks:        []string{"iam_rotate_access_key_90_days"},
}
var ISO27001_A_9_3_10 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.3",
	Name:          "User Responsibilities",
	Description:   "Ensure credentials unused for 90 days or greater are disabled",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.3",
	Objetive_Name: "User Responsibilities",
	Check_Summary: "Ensure credentials unused for 90 days or greater are disabled",
	Checks:        []string{"iam_user_accesskey_unused", "iam_user_console_access_unused"},
}
var ISO27001_A_9_4_1 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure IAM password policy expires passwords within 90 days or less",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure IAM password policy expires passwords within 90 days or less",
	Checks:        []string{"iam_password_policy_expires_passwords_within_90_days_or_less"},
}
var ISO27001_A_9_4_2 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure IAM password policy prevents password reuse",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure IAM password policy prevents password reuse",
	Checks:        []string{"iam_password_policy_reuse_24"},
}
var ISO27001_A_9_4_3 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure IAM password policy requires minimum length of 14 or greater",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure IAM password policy requires minimum length of 14 or greater",
	Checks:        []string{"iam_password_policy_minimum_length_14"},
}
var ISO27001_A_9_4_4 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure IAM password policy require at least one number",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure IAM password policy require at least one number",
	Checks:        []string{"iam_password_policy_number"},
}
var ISO27001_A_9_4_5 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure IAM password policy require at least one symbol",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure IAM password policy require at least one symbol",
	Checks:        []string{"iam_password_policy_symbol"},
}
var ISO27001_A_9_4_6 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure IAM password policy require at least one lowercase letter",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure IAM password policy require at least one lowercase letter",
	Checks:        []string{"iam_password_policy_lowercase"},
}
var ISO27001_A_9_4_7 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure IAM password policy requires at least one uppercase letter",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure IAM password policy requires at least one uppercase letter",
	Checks:        []string{"iam_password_policy_uppercase"},
}
var ISO27001_A_9_4_8 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Avoid the use of the 'root' account",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Avoid the use of the 'root' account",
	Checks:        []string{"iam_avoid_root_usage"},
}
var ISO27001_A_9_4_9 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure IAM policies are attached only to groups or roles",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure IAM policies are attached only to groups or roles",
	Checks:        []string{"iam_policy_attached_only_to_group_or_roles"},
}
var ISO27001_A_9_4_10 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure multi-factor authentication (MFA) is enabled for all IAM users that have console access",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure multi-factor authentication (MFA) is enabled for all IAM users that have console access",
	Checks:        []string{"iam_user_mfa_enabled_console_access"},
}
var ISO27001_A_9_4_11 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure MFA is enabled for the 'root' account",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure MFA is enabled for the 'root' account",
	Checks:        []string{"iam_root_mfa_enabled"},
}
var ISO27001_A_9_4_12 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure access keys are rotated every 90 days or less",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure access keys are rotated every 90 days or less",
	Checks:        []string{"iam_rotate_access_key_90_days"},
}
var ISO27001_A_9_4_13 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure credentials unused for 90 days or greater are disabled",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure credentials unused for 90 days or greater are disabled",
	Checks:        []string{"iam_user_accesskey_unused", "iam_user_console_access_unused"},
}
var ISO27001_A_9_4_14 = &NistComp{
	Framework:     "ISO27001",
	Provider:      "AWS",
	Frameworkdesc: "ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.",
	Id:            "A.9.4",
	Name:          "System and Application Access Control",
	Description:   "Ensure no root account access key exists",
	Category:      "A.9 Access Control",
	Objetive_ID:   "A.9.4",
	Objetive_Name: "System and Application Access Control",
	Check_Summary: "Ensure no root account access key exists",
	Checks:        []string{"iam_no_root_access_key"},
}
